[build-system]
requires = ["setuptools", "cython"]

[project]
name = "labtools"
version = '0.0.6'
requires-python = ">=3.11"
license = {text = "MIT"}

dependencies = [
	'numpy',
	'matplotlib',
	'kafe2',
]